workflows:
  android-release:
    name: Money Manager Production APK

    environment:
      node: 20.19.0
      java: 17
      groups:
        - money-manager-env

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Generate Android project
        script: |
          npx expo prebuild --platform android --clean --non-interactive

      - name: Build production APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk