workflows:
  android-debug:
    name: Money Manager Android Debug

    environment:
      node: 20.19.0
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk